
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab2p1(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

endmodule
module ripple_carry_adder_8bit (
    input [7:0] a, b,
    output [7:0] sum,
    output cout, overflow
);
    wire [7:0] carry;

    
    full_adder FA0 (.a(a[0]), .b(b[0]), .ci(1'b0),      .s(sum[0]), .co(carry[0]));
    full_adder FA1 (.a(a[1]), .b(b[1]), .ci(carry[0]),  .s(sum[1]), .co(carry[1]));
    full_adder FA2 (.a(a[2]), .b(b[2]), .ci(carry[1]),  .s(sum[2]), .co(carry[2]));
    full_adder FA3 (.a(a[3]), .b(b[3]), .ci(carry[2]),  .s(sum[3]), .co(carry[3]));
    full_adder FA4 (.a(a[4]), .b(b[4]), .ci(carry[3]),  .s(sum[4]), .co(carry[4]));
    full_adder FA5 (.a(a[5]), .b(b[5]), .ci(carry[4]),  .s(sum[5]), .co(carry[5]));
    full_adder FA6 (.a(a[6]), .b(b[6]), .ci(carry[5]),  .s(sum[6]), .co(carry[6]));
    full_adder FA7 (.a(a[7]), .b(b[7]), .ci(carry[6]),  .s(sum[7]), .co(carry[7]));

   
    assign cout     = carry[7];
    assign overflow = carry[7] ^ carry[6]; 
endmodule


